# Generated by Django 2.2.1 on 2019-10-04 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PailnumModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pail_num', models.IntegerField(max_length=200)),
                ('pail_detail_num', models.IntegerField(max_length=200)),
            ],
        ),
    ]
