# Generated by Django 2.2.1 on 2019-10-04 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pailnummodel',
            name='pail_detail_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pailnummodel',
            name='pail_num',
            field=models.IntegerField(),
        ),
    ]
