# Generated by Django 2.2.1 on 2019-12-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_sample4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_results', models.CharField(max_length=50, verbose_name='出荷実績')),
                ('delivery_record', models.CharField(max_length=20, verbose_name='納品実績')),
                ('deliverer', models.CharField(max_length=10, verbose_name='納品者')),
            ],
        ),
    ]
