# Generated by Django 2.2.1 on 2019-11-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191004_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pailnummodel',
            name='pail_detail_num',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pailnummodel',
            name='pail_num',
            field=models.CharField(max_length=10),
        ),
    ]
