# Generated by Django 2.2.1 on 2019-12-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_post1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post2',
            fields=[
                ('shipment_results', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='出荷実績')),
                ('delivery_record', models.CharField(max_length=20, verbose_name='納品実績')),
                ('deliverer', models.CharField(max_length=10, verbose_name='納品者')),
            ],
        ),
        migrations.DeleteModel(
            name='FileNameModel',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Post1',
        ),
        migrations.DeleteModel(
            name='sample2',
        ),
        migrations.DeleteModel(
            name='sample3',
        ),
        migrations.DeleteModel(
            name='sample4',
        ),
    ]
