# Generated by Django 2.2.1 on 2019-12-18 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191217_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post3',
            fields=[
                ('shipment_results', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='出荷実績')),
                ('delivery_record', models.DateTimeField(max_length=20, verbose_name='納品実績')),
                ('deliverer', models.CharField(max_length=10, verbose_name='納品確認者')),
            ],
        ),
        migrations.DeleteModel(
            name='Post2',
        ),
    ]
