# Generated by Django 2.2.1 on 2019-12-18 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191218_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post3',
            name='delivery_record',
            field=models.DateTimeField(max_length=20, null=True, verbose_name='納品実績'),
        ),
    ]
