# Generated by Django 2.2.1 on 2019-12-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_post1_casting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post1',
            name='correction',
            field=models.CharField(max_length=40, null=True, verbose_name='修正時刻'),
        ),
        migrations.AlterField(
            model_name='post1',
            name='delivery_record',
            field=models.CharField(max_length=40, null=True, verbose_name='納品実績'),
        ),
        migrations.AlterField(
            model_name='post1',
            name='material_inspection',
            field=models.CharField(max_length=40, null=True, verbose_name='材料検査'),
        ),
        migrations.AlterField(
            model_name='post1',
            name='start_casting',
            field=models.CharField(max_length=40, null=True, verbose_name='打設開始時刻'),
        ),
    ]
