# Generated by Django 2.2.1 on 2019-12-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20191219_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post1',
            name='caster',
            field=models.CharField(max_length=10, null=True, verbose_name='打設者'),
        ),
        migrations.AlterField(
            model_name='post1',
            name='corrector',
            field=models.CharField(max_length=10, null=True, verbose_name='修正者'),
        ),
        migrations.AlterField(
            model_name='post1',
            name='cross_section',
            field=models.CharField(max_length=5, null=True, verbose_name='断面'),
        ),
        migrations.AlterField(
            model_name='post1',
            name='deliverer',
            field=models.CharField(max_length=10, null=True, verbose_name='納品確認者'),
        ),
        migrations.AlterField(
            model_name='post1',
            name='inspector',
            field=models.CharField(max_length=10, null=True, verbose_name='検査者'),
        ),
        migrations.AlterField(
            model_name='post1',
            name='pail_num',
            field=models.CharField(max_length=5, null=True, verbose_name='杭番号'),
        ),
    ]
