# Generated by Django 2.2.1 on 2019-12-27 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20191220_0817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post4',
            old_name='shipment_results',
            new_name='serial_num',
        ),
    ]
